/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registrocivil;
import com.mycompany.registrocivil.Clases.ConjuntoRegiones;
import com.mycompany.registrocivil.Clases.Region;
import java.awt.event.ActionEvent;
import com.mycompany.excepciones.EliminarRegionException;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class VentanaEliminarRegion extends javax.swing.JFrame {
    
    ConjuntoRegiones conjuntoRegiones;
    
    public VentanaEliminarRegion(ConjuntoRegiones conjunto){
        this.conjuntoRegiones = conjunto;
        initComponents();
        String [] nombres = conjuntoRegiones.obtenerNombresRegiones();
        comboBoxRegiones.addItem("Seleccione");
        for(String nombre : nombres)
            comboBoxRegiones.addItem(nombre);
        casillaNombreDatos.setEnabled(false);
        casillaCantidad.setEnabled(false);
        EliminarRegion.setEnabled(false);
        lblEliminarRegion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        IconoMenu = new javax.swing.JLabel();
        Agregar = new javax.swing.JLabel();
        lblMostrarListado = new javax.swing.JLabel();
        lblAgregarPersona = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Listar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        AgregarRegion = new javax.swing.JLabel();
        lblAgregarRegion = new javax.swing.JLabel();
        EliminarRegion = new javax.swing.JLabel();
        lblEliminarRegion = new javax.swing.JLabel();
        EditarRegion = new javax.swing.JLabel();
        lblEditarRegion = new javax.swing.JLabel();
        PanelGobierno = new javax.swing.JPanel();
        Gobierno = new javax.swing.JLabel();
        Cuadro = new javax.swing.JPanel();
        panelEliminar = new javax.swing.JPanel();
        lblTituloEliminar = new javax.swing.JLabel();
        lblRegion1 = new javax.swing.JLabel();
        comboBoxRegiones = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        lblCantPersonas = new javax.swing.JLabel();
        casillaCantidad = new javax.swing.JTextField();
        lblTituloDatos = new javax.swing.JLabel();
        lblNombreDatos = new javax.swing.JLabel();
        casillaNombreDatos = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(1000, 625));
        setName(""); // NOI18N

        Fondo.setBackground(new java.awt.Color(231, 231, 231));
        Fondo.setPreferredSize(new java.awt.Dimension(1000, 625));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLateral.setBackground(new java.awt.Color(54, 70, 78));

        IconoMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IconoMenu.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/menu.png"));
        IconoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IconoMenuMousePressed(evt);
            }
        });

        Agregar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Agregar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/agregar.png"));
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarMousePressed(evt);
            }
        });

        lblMostrarListado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMostrarListado.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrarListado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMostrarListado.setText("Mostrar Listado");
        lblMostrarListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMostrarListadoMousePressed(evt);
            }
        });

        lblAgregarPersona.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAgregarPersona.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarPersona.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAgregarPersona.setText("Agregar Persona");
        lblAgregarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAgregarPersonaMousePressed(evt);
            }
        });

        lblInicio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInicio.setText("Inicio");
        lblInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInicioMousePressed(evt);
            }
        });

        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Inicio.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/inicio.png"));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InicioMousePressed(evt);
            }
        });

        Listar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Listar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/mostrar.png"));
        Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListarMousePressed(evt);
            }
        });

        Editar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Editar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/estado.png"));
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarMousePressed(evt);
            }
        });

        lblEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditar.setText("Editar Persona");
        lblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEditarMousePressed(evt);
            }
        });

        lblEliminar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEliminar.setText("Eliminar Persona");
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEliminarMousePressed(evt);
            }
        });

        Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Eliminar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/eliminar.png"));
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarMousePressed(evt);
            }
        });

        AgregarRegion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        AgregarRegion.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/agregarRegion.png"));
        AgregarRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarRegionMousePressed(evt);
            }
        });

        lblAgregarRegion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAgregarRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarRegion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAgregarRegion.setText("Agregar Región");
        lblAgregarRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAgregarRegionMousePressed(evt);
            }
        });

        EliminarRegion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EliminarRegion.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/eliminarRegion.png"));
        EliminarRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EliminarRegionMousePressed(evt);
            }
        });

        lblEliminarRegion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEliminarRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarRegion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEliminarRegion.setText("Eliminar Región");
        lblEliminarRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEliminarRegionMousePressed(evt);
            }
        });

        EditarRegion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EditarRegion.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/editarRegion.png"));
        EditarRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EditarRegionMousePressed(evt);
            }
        });

        lblEditarRegion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEditarRegion.setForeground(new java.awt.Color(255, 255, 255));
        lblEditarRegion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditarRegion.setText("Editar Región");
        lblEditarRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEditarRegionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgregarPersona)
                            .addComponent(lblMostrarListado)
                            .addComponent(lblInicio)
                            .addComponent(lblEditar)
                            .addComponent(lblEliminar)
                            .addComponent(lblAgregarRegion)
                            .addComponent(lblEliminarRegion)
                            .addComponent(lblEditarRegion))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMostrarListado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EliminarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEliminarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditarRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        Fondo.add(MenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 630));

        PanelGobierno.setBackground(new java.awt.Color(0, 0, 0));
        PanelGobierno.setPreferredSize(new java.awt.Dimension(380, 50));

        Gobierno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Gobierno.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/gobierno.png"));
        Gobierno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GobiernoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelGobiernoLayout = new javax.swing.GroupLayout(PanelGobierno);
        PanelGobierno.setLayout(PanelGobiernoLayout);
        PanelGobiernoLayout.setHorizontalGroup(
            PanelGobiernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGobiernoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Gobierno, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelGobiernoLayout.setVerticalGroup(
            PanelGobiernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGobiernoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Gobierno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Fondo.add(PanelGobierno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        Cuadro.setBackground(new java.awt.Color(241, 241, 241));

        panelEliminar.setBackground(new java.awt.Color(241, 241, 241));
        panelEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTituloEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloEliminar.setText("Eliminar región");

        lblRegion1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegion1.setText("Región:");

        comboBoxRegiones.setPreferredSize(new java.awt.Dimension(72, 25));

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblTituloEliminar))
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion1)
                    .addComponent(comboBoxRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                try{btnEliminarMousePressed(evt);}
                catch(EliminarRegionException e)
                {
                    if(e.getExcepction().equals("región"))
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese una "+e.getExcepction(), "Error al ingresar región", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLimpiarMousePressed(evt);
            }
        });

        panelDatos.setBackground(new java.awt.Color(241, 241, 241));
        panelDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCantPersonas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCantPersonas.setText("Cantidad de personas:");

        casillaCantidad.setMinimumSize(new java.awt.Dimension(64, 24));
        casillaCantidad.setPreferredSize(new java.awt.Dimension(64, 25));

        lblTituloDatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloDatos.setText("Datos región ingresada");

        lblNombreDatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreDatos.setText("Nombre:");

        casillaNombreDatos.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(lblCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(lblNombreDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaNombreDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 318, Short.MAX_VALUE))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTituloDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(470, Short.MAX_VALUE)))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDatos)
                    .addComponent(casillaNombreDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casillaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantPersonas))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblTituloDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout CuadroLayout = new javax.swing.GroupLayout(Cuadro);
        Cuadro.setLayout(CuadroLayout);
        CuadroLayout.setHorizontalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        CuadroLayout.setVerticalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        Fondo.add(Cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 770, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean menuDesplegado = false;
    private void IconoMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMousePressed
        int velocidadAnimacion = 4; // Velocidad de la animación (ajusta según tus necesidades)
        int desplazamientoFinal = -160; // La cantidad que quieres desplazar hacia la izquierda
        // Cambia la dirección de la animación en función del estado actual del menú
        int desplazamientoInicial = menuDesplegado ? desplazamientoFinal : 0;
        int desplazamientoObjetivo = menuDesplegado ? 0 : desplazamientoFinal;
        
        if(menuDesplegado == false)
        {
            lblAgregarPersona.setText(""); 
            lblMostrarListado.setText("");
            lblInicio.setText(""); 
            lblEliminar.setText(""); 
            lblEditar.setText("");
            lblAgregarRegion.setText(""); 
            lblEliminarRegion.setText(""); 
            lblEditarRegion.setText(""); 
        }
        
        Timer timer = new Timer(10, new ActionListener() {
            int desplazamientoActual = desplazamientoInicial;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (desplazamientoActual != desplazamientoObjetivo) {
                    MenuLateral.setLocation(desplazamientoActual, MenuLateral.getY());
                    Agregar.setLocation(-desplazamientoActual, Agregar.getY());
                    AgregarRegion.setLocation(-desplazamientoActual, AgregarRegion.getY());
                    EliminarRegion.setLocation(-desplazamientoActual, EliminarRegion.getY());
                    EditarRegion.setLocation(-desplazamientoActual, EditarRegion.getY());
                    Inicio.setLocation(-desplazamientoActual, Inicio.getY());
                    Listar.setLocation(-desplazamientoActual, Listar.getY());
                    Eliminar.setLocation(-desplazamientoActual, Eliminar.getY());
                    Editar.setLocation(-desplazamientoActual, Editar.getY());
                    if (menuDesplegado == false) {               
                        Cuadro.setLocation(Cuadro.getX() - velocidadAnimacion, Cuadro.getY());
                        Cuadro.setSize(Cuadro.getWidth() + velocidadAnimacion, Cuadro.getHeight());
                        PanelGobierno.setLocation(PanelGobierno.getX() - velocidadAnimacion, PanelGobierno.getY());
                        panelEliminar.setSize(panelEliminar.getWidth() + velocidadAnimacion, panelEliminar.getHeight());
                        panelDatos.setSize(panelDatos.getWidth() + velocidadAnimacion, panelDatos.getHeight());
                        btnEliminar.setLocation(btnEliminar.getX() + velocidadAnimacion, btnEliminar.getY());
                        btnLimpiar.setLocation(btnLimpiar.getX() + velocidadAnimacion, btnLimpiar.getY());
                        casillaNombreDatos.setSize(casillaNombreDatos.getWidth() + velocidadAnimacion, casillaNombreDatos.getHeight());
                        casillaCantidad.setSize(casillaCantidad.getWidth() + velocidadAnimacion, casillaCantidad.getHeight());
                        
                    } else {
                        Cuadro.setLocation(Cuadro.getX() + velocidadAnimacion, Cuadro.getY());
                        Cuadro.setSize(Cuadro.getWidth() - velocidadAnimacion, Cuadro.getHeight());
                        PanelGobierno.setLocation(PanelGobierno.getX() + velocidadAnimacion, PanelGobierno.getY());
                        PanelGobierno.setSize(PanelGobierno.getWidth(), PanelGobierno.getHeight());
                        panelEliminar.setSize(panelEliminar.getWidth() - velocidadAnimacion, panelEliminar.getHeight());
                        panelDatos.setSize(panelDatos.getWidth() - velocidadAnimacion, panelDatos.getHeight());
                        casillaNombreDatos.setSize(casillaNombreDatos.getWidth() - velocidadAnimacion, casillaNombreDatos.getHeight());
                        casillaCantidad.setSize(casillaCantidad.getWidth() - velocidadAnimacion, casillaCantidad.getHeight());
                        btnEliminar.setLocation(btnEliminar.getX() - velocidadAnimacion, btnEliminar.getY());
                        btnLimpiar.setLocation(btnLimpiar.getX() - velocidadAnimacion, btnLimpiar.getY());
                        
                    }
                    if (menuDesplegado) {
                        desplazamientoActual += velocidadAnimacion;
                    } else {
                        desplazamientoActual -= velocidadAnimacion;
                    }
                    
                } else {
                    ((Timer) e.getSource()).stop();                  
                    if(menuDesplegado==true)
                    {
                        Timer textTimer = new Timer(100, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            lblAgregarPersona.setText("Agregar Persona");
                            lblMostrarListado.setText("Mostrar Listado");
                            lblInicio.setText("Inicio");
                            lblEliminar.setText("Eliminar Persona"); 
                            lblEditar.setText("Editar Persona"); 
                            lblEditarRegion.setText("Editar Región");
                            lblAgregarRegion.setText("Agregar Región");
                            lblEliminarRegion.setText("EliminarRegión"); 
                        }
                        });
                        textTimer.setRepeats(false); // Ejecutar una sola vez
                        textTimer.start();
                    }
                    menuDesplegado = !menuDesplegado;
                }
                
            }
        });
        timer.start();
    }//GEN-LAST:event_IconoMenuMousePressed
    
    private void ListarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarMousePressed
        VentanaListarPersona ven = new VentanaListarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListarMousePressed

    private void InicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMousePressed
        VentanaPrincipal ven = new VentanaPrincipal(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicioMousePressed

    private void EditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMousePressed
        VentanaEditarPersona ven = new VentanaEditarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditarMousePressed

    private void GobiernoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GobiernoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GobiernoMousePressed

    private void AgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMousePressed
        VentanaAgregarPersona ven = new VentanaAgregarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) throws EliminarRegionException{//GEN-FIRST:event_btnEliminarMousePressed
        Object selectedItem = comboBoxRegiones.getSelectedItem();
        String selectedRegion = selectedItem.toString();
        Region region = conjuntoRegiones.buscarRegion(selectedRegion);
        if(selectedRegion.equals("Seleccione"))
        {
            comboBoxRegiones.setSelectedIndex(0);
            casillaNombreDatos.setText("");
            casillaCantidad.setText("");
            throw new EliminarRegionException(selectedRegion);
        }
        
        casillaNombreDatos.setText(region.getName());
        casillaCantidad.setText(Integer.toString(region.getCant()));
        conjuntoRegiones.eliminarRegion(selectedRegion);
        comboBoxRegiones.setSelectedIndex(0);
        File folderRegion = new File("CarpetaRegiones/" + selectedRegion+".xls");
        File folderVotante = new File("CarpetaRegionesVotantes/" + selectedRegion+".xls");
        folderRegion.delete();
        folderVotante.delete();
        conjuntoRegiones.exportarXlsTodasLasRegiones();
        conjuntoRegiones.exportarXlsVotantesTodasLasRegiones();
        JOptionPane.showMessageDialog(null, "Región eliminada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        VentanaEliminarRegion ven = new VentanaEliminarRegion(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMousePressed
        casillaNombreDatos.setText("");
        casillaCantidad.setText("");
        comboBoxRegiones.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarMousePressed

    private void AgregarRegionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarRegionMousePressed
        VentanaAgregarRegion ven = new VentanaAgregarRegion(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarRegionMousePressed

    private void lblAgregarRegionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarRegionMousePressed
        VentanaAgregarRegion ven = new VentanaAgregarRegion(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgregarRegionMousePressed

    private void EliminarRegionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarRegionMousePressed

    }//GEN-LAST:event_EliminarRegionMousePressed

    private void lblEliminarRegionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarRegionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEliminarRegionMousePressed

    private void EditarRegionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarRegionMousePressed
        VentanaEditarRegion ven = new VentanaEditarRegion(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditarRegionMousePressed

    private void lblEditarRegionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarRegionMousePressed
        VentanaEditarRegion ven = new VentanaEditarRegion(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblEditarRegionMousePressed

    private void lblInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInicioMousePressed
        VentanaPrincipal ven = new VentanaPrincipal(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblInicioMousePressed

    private void lblAgregarPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarPersonaMousePressed
        VentanaAgregarPersona ven = new VentanaAgregarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgregarPersonaMousePressed

    private void lblEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMousePressed
        VentanaEliminarPersona ven = new VentanaEliminarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblEliminarMousePressed

    private void lblMostrarListadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostrarListadoMousePressed
        VentanaListarPersona ven = new VentanaListarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblMostrarListadoMousePressed

    private void lblEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarMousePressed
        VentanaEditarPersona ven = new VentanaEditarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblEditarMousePressed

    private void EliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMousePressed
        VentanaEliminarPersona ven = new VentanaEliminarPersona(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EliminarMousePressed


// Code adding the component to the parent container - not shown here

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarRegion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConjuntoRegiones conjunto = new ConjuntoRegiones();
                new VentanaEliminarRegion(conjunto).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel AgregarRegion;
    private javax.swing.JPanel Cuadro;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel EditarRegion;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel EliminarRegion;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Gobierno;
    private javax.swing.JLabel IconoMenu;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Listar;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel PanelGobierno;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextField casillaCantidad;
    private javax.swing.JTextField casillaNombreDatos;
    private javax.swing.JComboBox<String> comboBoxRegiones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregarPersona;
    private javax.swing.JLabel lblAgregarRegion;
    private javax.swing.JLabel lblCantPersonas;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEditarRegion;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblEliminarRegion;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblMostrarListado;
    private javax.swing.JLabel lblNombreDatos;
    private javax.swing.JLabel lblRegion1;
    private javax.swing.JLabel lblTituloDatos;
    private javax.swing.JLabel lblTituloEliminar;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEliminar;
    // End of variables declaration//GEN-END:variables
}
