/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registrocivil.Clases;
import com.mycompany.registrocivil.Test;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;



public class Agregar extends javax.swing.JFrame {
    

    public Agregar() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        IconoMenu = new javax.swing.JLabel();
        Listar = new javax.swing.JLabel();
        Agregar = new javax.swing.JLabel();
        Texto2 = new javax.swing.JLabel();
        Texto1 = new javax.swing.JLabel();
        Cuadro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(1000, 625));
        setName(""); // NOI18N

        Fondo.setBackground(new java.awt.Color(231, 231, 231));
        Fondo.setPreferredSize(new java.awt.Dimension(1000, 625));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLateral.setBackground(new java.awt.Color(54, 70, 78));

        IconoMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IconoMenu.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/menu.png"));
        IconoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IconoMenuMousePressed(evt);
            }
        });

        Listar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Listar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/mostrar.png"));
        Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListarMousePressed(evt);
            }
        });

        Agregar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Agregar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/agregar.png"));
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarMousePressed(evt);
            }
        });

        Texto2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Texto2.setForeground(new java.awt.Color(255, 255, 255));
        Texto2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Texto2.setText("Mostrar listado");
        Texto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Texto2MousePressed(evt);
            }
        });

        Texto1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Texto1.setForeground(new java.awt.Color(255, 255, 255));
        Texto1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Texto1.setText("Agregar persona");
        Texto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Texto1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Texto1)
                            .addComponent(Texto2))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(483, Short.MAX_VALUE))
        );

        Fondo.add(MenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 630));

        Cuadro.setBackground(new java.awt.Color(241, 241, 241));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CuadroLayout = new javax.swing.GroupLayout(Cuadro);
        Cuadro.setLayout(CuadroLayout);
        CuadroLayout.setHorizontalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CuadroLayout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        CuadroLayout.setVerticalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );

        Fondo.add(Cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 770, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean menuDesplegado = false;
    private void IconoMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMousePressed
        int velocidadAnimacion = 4; // Velocidad de la animación (ajusta según tus necesidades)
        int desplazamientoFinal = -160; // La cantidad que quieres desplazar hacia la izquierda
        
        // Cambia la dirección de la animación en función del estado actual del menú
        int desplazamientoInicial = menuDesplegado ? desplazamientoFinal : 0;
        int desplazamientoObjetivo = menuDesplegado ? 0 : desplazamientoFinal;
        
        if(menuDesplegado == false)
        {
            Texto1.setText(""); 
            Texto2.setText(""); 
        }
        
        Timer timer = new Timer(10, new ActionListener() {
            int desplazamientoActual = desplazamientoInicial;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (desplazamientoActual != desplazamientoObjetivo) {
                    MenuLateral.setLocation(desplazamientoActual, MenuLateral.getY());
                    Agregar.setLocation(-desplazamientoActual, Agregar.getY());
                    Listar.setLocation(-desplazamientoActual, Listar.getY());
                    if (menuDesplegado == false) {
                        Cuadro.setLocation(Cuadro.getX() - velocidadAnimacion, Cuadro.getY());
                        Cuadro.setSize(Cuadro.getWidth() + velocidadAnimacion, Cuadro.getHeight());
                    } else {
                        Cuadro.setLocation(Cuadro.getX() + velocidadAnimacion, Cuadro.getY());
                        Cuadro.setSize(Cuadro.getWidth() - velocidadAnimacion, Cuadro.getHeight());
                    }
                    if (menuDesplegado) {
                        desplazamientoActual += velocidadAnimacion;
                    } else {
                        desplazamientoActual -= velocidadAnimacion;
                    }
                    
                } else {
                    ((Timer) e.getSource()).stop();                  
                    if(menuDesplegado==true)
                    {
                        Timer textTimer = new Timer(100, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            Texto1.setText("Agregar persona");
                            Texto2.setText("Mostrar listado");
                        }
                        });
                        textTimer.setRepeats(false); // Ejecutar una sola vez
                        textTimer.start();
                    }
                    menuDesplegado = !menuDesplegado;
                }
                
            }
        });
        timer.start();
    }//GEN-LAST:event_IconoMenuMousePressed
    
    private void Texto2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto2MousePressed

    private void Texto1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Texto1MousePressed

    private void AgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMousePressed
    // Obtén las propiedades del Cuadro antes de ocultarlo
    int cuadroX = Cuadro.getX();
    int cuadroY = Cuadro.getY();
    int cuadroWidth = Cuadro.getWidth();
    int cuadroHeight = Cuadro.getHeight();
    
    // Oculta el Cuadro
    Cuadro.setVisible(false);
    
    // Crea una nueva instancia del panel PanelDePrueba y establece las propiedades
    Test panelAgregar = new Test();
    panelAgregar.setBounds(cuadroX, cuadroY, cuadroWidth, cuadroHeight); // Establece posición y tamaño
    
    // Agrega el panelAgregar al JFrame
    this.add(panelAgregar);
    
    // Asegúrate de validar y repintar el contenedor principal
    this.validate();
    this.repaint();
    }//GEN-LAST:event_AgregarMousePressed

    private void ListarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JPanel Cuadro;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel IconoMenu;
    private javax.swing.JLabel Listar;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
