/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.registrocivil;
import com.mycompany.registrocivil.Clases.ConjuntoRegiones;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class VentanaEliminar extends javax.swing.JFrame {
    
    ConjuntoRegiones conjuntoRegiones;
    
    public VentanaEliminar(ConjuntoRegiones conjunto){
        this.conjuntoRegiones = conjunto;
        initComponents();
        String [] nombres = conjuntoRegiones.obtenerNombresRegiones();
        for(String nombre : nombres)
            comboBoxRegiones.addItem(nombre);
        casillaNacimiento.setEnabled(false);
        casillaDefuncion.setEnabled(false);
        casillaRutDatos.setEnabled(false);
        casillaNombre.setEnabled(false);
        casillaRegion.setEnabled(false);
        casillaEstado.setEnabled(false);
        Eliminar.setEnabled(false);
        lblEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        IconoMenu = new javax.swing.JLabel();
        Agregar = new javax.swing.JLabel();
        lblMostrarListado = new javax.swing.JLabel();
        lblAgregarPersona = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Listar = new javax.swing.JLabel();
        EstadoCivil = new javax.swing.JLabel();
        lblEditar = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        PanelGobierno = new javax.swing.JPanel();
        Gobierno = new javax.swing.JLabel();
        Cuadro = new javax.swing.JPanel();
        panelEliminar = new javax.swing.JPanel();
        lblRut = new javax.swing.JLabel();
        casillaRut = new javax.swing.JTextField();
        lblTituloEliminar = new javax.swing.JLabel();
        comboBoxRegiones = new javax.swing.JComboBox<>();
        lblRegion1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        lblRutDato = new javax.swing.JLabel();
        casillaRutDatos = new javax.swing.JTextField();
        lblTituloDatos = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        casillaNombre = new javax.swing.JTextField();
        lblNacimiento = new javax.swing.JLabel();
        casillaNacimiento = new com.toedter.calendar.JDateChooser();
        lblRegion = new javax.swing.JLabel();
        casillaRegion = new javax.swing.JTextField();
        lblDefuncion = new javax.swing.JLabel();
        casillaDefuncion = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        casillaEstado = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(1000, 625));
        setName(""); // NOI18N

        Fondo.setBackground(new java.awt.Color(231, 231, 231));
        Fondo.setPreferredSize(new java.awt.Dimension(1000, 625));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLateral.setBackground(new java.awt.Color(54, 70, 78));

        IconoMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IconoMenu.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/menu.png"));
        IconoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IconoMenuMousePressed(evt);
            }
        });

        Agregar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Agregar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/agregar.png"));
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarMousePressed(evt);
            }
        });

        lblMostrarListado.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblMostrarListado.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrarListado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMostrarListado.setText("Mostrar Listado");

        lblAgregarPersona.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAgregarPersona.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarPersona.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAgregarPersona.setText("Agregar Persona");

        lblInicio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInicio.setText("Inicio");

        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Inicio.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/inicio.png"));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InicioMousePressed(evt);
            }
        });

        Listar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Listar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/mostrar.png"));
        Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ListarMousePressed(evt);
            }
        });

        EstadoCivil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EstadoCivil.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/estado.png"));
        EstadoCivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EstadoCivilMousePressed(evt);
            }
        });

        lblEditar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEditar.setForeground(new java.awt.Color(255, 255, 255));
        lblEditar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEditar.setText("Editar Persona");

        lblEliminar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEliminar.setText("Eliminar Persona");

        Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Eliminar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/eliminar.png"));

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgregarPersona)
                            .addComponent(lblMostrarListado)
                            .addComponent(lblInicio)
                            .addComponent(lblEditar)
                            .addComponent(lblEliminar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IconoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMostrarListado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(369, Short.MAX_VALUE))
        );

        Fondo.add(MenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 630));

        PanelGobierno.setBackground(new java.awt.Color(0, 0, 0));
        PanelGobierno.setPreferredSize(new java.awt.Dimension(380, 50));

        Gobierno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Gobierno.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "/src/com/mycompany/iconos/gobierno.png"));
        Gobierno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GobiernoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelGobiernoLayout = new javax.swing.GroupLayout(PanelGobierno);
        PanelGobierno.setLayout(PanelGobiernoLayout);
        PanelGobiernoLayout.setHorizontalGroup(
            PanelGobiernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGobiernoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Gobierno, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelGobiernoLayout.setVerticalGroup(
            PanelGobiernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGobiernoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Gobierno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Fondo.add(PanelGobierno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        Cuadro.setBackground(new java.awt.Color(241, 241, 241));

        panelEliminar.setBackground(new java.awt.Color(241, 241, 241));
        panelEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRut.setText("Rut:");

        casillaRut.setMinimumSize(new java.awt.Dimension(64, 24));
        casillaRut.setPreferredSize(new java.awt.Dimension(64, 25));

        lblTituloEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloEliminar.setText("Eliminar persona");

        comboBoxRegiones.setPreferredSize(new java.awt.Dimension(72, 25));

        lblRegion1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegion1.setText("Región:");

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addComponent(lblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEliminarLayout.createSequentialGroup()
                        .addComponent(lblRegion1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxRegiones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminarLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEliminarLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(casillaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegion1))
                .addGap(28, 28, 28))
            .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminarLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblTituloEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLimpiarMousePressed(evt);
            }
        });

        panelDatos.setBackground(new java.awt.Color(241, 241, 241));
        panelDatos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblRutDato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRutDato.setText("Rut:");

        casillaRutDatos.setMinimumSize(new java.awt.Dimension(64, 24));
        casillaRutDatos.setPreferredSize(new java.awt.Dimension(64, 25));

        lblTituloDatos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloDatos.setText("Datos Persona Eliminada");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");

        casillaNombre.setPreferredSize(new java.awt.Dimension(64, 25));

        lblNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNacimiento.setText("Fecha de nacimiento:");

        casillaNacimiento.setPreferredSize(new java.awt.Dimension(85, 25));

        lblRegion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegion.setText("Región:");

        casillaRegion.setMinimumSize(new java.awt.Dimension(64, 25));
        casillaRegion.setPreferredSize(new java.awt.Dimension(64, 25));

        lblDefuncion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDefuncion.setText("Defunción:");

        casillaDefuncion.setMinimumSize(new java.awt.Dimension(64, 25));
        casillaDefuncion.setPreferredSize(new java.awt.Dimension(64, 25));

        lblEstadoCivil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoCivil.setText("Estado Civil:");

        casillaEstado.setMinimumSize(new java.awt.Dimension(64, 25));
        casillaEstado.setPreferredSize(new java.awt.Dimension(64, 25));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(lblNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(lblRutDato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(casillaRutDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(lblRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaRegion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDefuncion)
                    .addComponent(lblEstadoCivil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casillaDefuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casillaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(lblTituloDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(480, Short.MAX_VALUE)))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(casillaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDefuncion)
                    .addComponent(casillaDefuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casillaRutDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRutDato)
                    .addComponent(lblEstadoCivil)
                    .addComponent(casillaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNacimiento)
                    .addComponent(casillaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegion)
                    .addComponent(casillaRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDatosLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblTituloDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout CuadroLayout = new javax.swing.GroupLayout(Cuadro);
        Cuadro.setLayout(CuadroLayout);
        CuadroLayout.setHorizontalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        CuadroLayout.setVerticalGroup(
            CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CuadroLayout.createSequentialGroup()
                .addGroup(CuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CuadroLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        Fondo.add(Cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 770, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean menuDesplegado = false;
    private void IconoMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconoMenuMousePressed
        int velocidadAnimacion = 4; // Velocidad de la animación (ajusta según tus necesidades)
        int desplazamientoFinal = -160; // La cantidad que quieres desplazar hacia la izquierda
        
        // Cambia la dirección de la animación en función del estado actual del menú
        int desplazamientoInicial = menuDesplegado ? desplazamientoFinal : 0;
        int desplazamientoObjetivo = menuDesplegado ? 0 : desplazamientoFinal;
        
        if(menuDesplegado == false)
        {
            lblAgregarPersona.setText(""); 
            lblMostrarListado.setText("");
            lblInicio.setText(""); 
            lblEliminar.setText(""); 
            lblEditar.setText(""); 
        }
        
        Timer timer = new Timer(10, new ActionListener() {
            int desplazamientoActual = desplazamientoInicial;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (desplazamientoActual != desplazamientoObjetivo) {
                    MenuLateral.setLocation(desplazamientoActual, MenuLateral.getY());
                    Agregar.setLocation(-desplazamientoActual, Agregar.getY());
                    Inicio.setLocation(-desplazamientoActual, Inicio.getY());
                    Listar.setLocation(-desplazamientoActual, Listar.getY());
                    Eliminar.setLocation(-desplazamientoActual, Eliminar.getY());
                    EstadoCivil.setLocation(-desplazamientoActual, EstadoCivil.getY());
                    if (menuDesplegado == false) {               
                        Cuadro.setLocation(Cuadro.getX() - velocidadAnimacion, Cuadro.getY());
                        Cuadro.setSize(Cuadro.getWidth() + velocidadAnimacion, Cuadro.getHeight());
                        PanelGobierno.setLocation(PanelGobierno.getX() - velocidadAnimacion, PanelGobierno.getY());
                    } else {
                        Cuadro.setLocation(Cuadro.getX() + velocidadAnimacion, Cuadro.getY());
                        Cuadro.setSize(Cuadro.getWidth() - velocidadAnimacion, Cuadro.getHeight());
                        PanelGobierno.setLocation(PanelGobierno.getX() + velocidadAnimacion, PanelGobierno.getY());
                        PanelGobierno.setSize(PanelGobierno.getWidth(), PanelGobierno.getHeight());
                    }
                    if (menuDesplegado) {
                        desplazamientoActual += velocidadAnimacion;
                    } else {
                        desplazamientoActual -= velocidadAnimacion;
                    }
                    
                } else {
                    ((Timer) e.getSource()).stop();                  
                    if(menuDesplegado==true)
                    {
                        Timer textTimer = new Timer(100, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent evt) {
                            lblAgregarPersona.setText("Agregar Persona");
                            lblMostrarListado.setText("Mostrar Listado");
                            lblInicio.setText("Inicio");
                            lblEliminar.setText("Eliminar Persona"); 
                            lblEditar.setText("Cambiar E. Civil"); 
                        }
                        });
                        textTimer.setRepeats(false); // Ejecutar una sola vez
                        textTimer.start();
                    }
                    menuDesplegado = !menuDesplegado;
                }
                
            }
        });
        timer.start();
    }//GEN-LAST:event_IconoMenuMousePressed
    
    private void ListarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarMousePressed
        VentanaListar ven = new VentanaListar(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ListarMousePressed

    private void InicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMousePressed
        VentanaPrincipal ven = new VentanaPrincipal(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InicioMousePressed

    private void EstadoCivilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadoCivilMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoCivilMousePressed

    private void GobiernoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GobiernoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GobiernoMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMousePressed
        casillaRut.setText("");
    }//GEN-LAST:event_btnLimpiarMousePressed

    private void AgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMousePressed
        VentanaAgregar ven = new VentanaAgregar(conjuntoRegiones);
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AgregarMousePressed


// Code adding the component to the parent container - not shown here

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConjuntoRegiones conjunto = new ConjuntoRegiones();
                new VentanaEliminar(conjunto).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JPanel Cuadro;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel EstadoCivil;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Gobierno;
    private javax.swing.JLabel IconoMenu;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Listar;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel PanelGobierno;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextField casillaDefuncion;
    private javax.swing.JTextField casillaEstado;
    private com.toedter.calendar.JDateChooser casillaNacimiento;
    private javax.swing.JTextField casillaNombre;
    private javax.swing.JTextField casillaRegion;
    private javax.swing.JTextField casillaRut;
    private javax.swing.JTextField casillaRutDatos;
    private javax.swing.JComboBox<String> comboBoxRegiones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgregarPersona;
    private javax.swing.JLabel lblDefuncion;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblMostrarListado;
    private javax.swing.JLabel lblNacimiento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblRegion1;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblRutDato;
    private javax.swing.JLabel lblTituloDatos;
    private javax.swing.JLabel lblTituloEliminar;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelEliminar;
    // End of variables declaration//GEN-END:variables
}
